#executable files for this directory
#tells make to use the file "../GNU_nakefile_template",which
OBJECTS = div4one.exe multi4one.exe sub4one.exe \
		 sum4one.exe


#defines general reles for making .o and .exe files
include ../GNU_makefile_template
	
