# executable files for this directory
OBJECTS = mood.exe sub4one.exe 

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ./GNU_makefile_template

div4one.exe sub4one.exe: Sales_item.h
