# executable files for this directory
OBJECTS = doWhile4ap.exe while4ap_with_step.exe cout_cerr_clog.exe div4one.exe mood.exe while4ap.exe  

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ./GNU_makefile_template

doWhile4ap.exe while4ap_with_step.exe cout_cerr_clog.exe div4one.exe mood.exe while4ap.exe: Sales_item.h  
