# executable files for this directory
OBJECTS = ex1.2.exe ex1.3.exe ex1.4.exe ex1.5.exe \
		  ex1.6.exe  ex1.8a.exe ex1.8b.exe ex1.8c.exe \
		  ex1.9.exe ex1.10a.exe ex1.10b.exe ex1.12.exe

# tells make to use the file "../GNU_makefile_template", which
#defines general rules for making .o and .exe files
include GNU_makefile_template

# add_item.exe add_item2.exe avg_price.exe item_io.exe: Sales_item.h
