# executable files for this directory
OBJECTS = cout_cerr_clog.exe emotion.exe  main.exe  sum4one2.exe \
	diff4plusplus.exe for4ap.exe  multi4one.exe  while4ap.exe    \
	div4one.exe  for4ap_with_step.exe sub4one.exe  while4sum.exe \
	dowhile4ap.exe  if4ap.exe  sum4one.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

add_item.exe add_item2.exe avg_price.exe item_io.exe: Sales_item.h
