# executable files for this directory
OBJECTS = sum4one.exe sub4one.exe multi4one.exe div4one.exe for4ap.exe  if4ap.exe dowhile4ap.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include GNU_makefile_template

