# executable files for this directory
OBJECTS =cout_cerr_clog.exe div4one.exe doWhile4ap.exe doWhile.exe for10-0.exe for4ap_with_step.exe main.exe mood.exe sub4one.exe sum4one.exe  
  

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ./GNU_makefile_template
cout_cerr_clog.exe div4one.exe doWhile4ap.exe doWhile.exe for10-0.exe for4ap_with_step.exe main.exe mood.exe sub4one.exe sum4one.exe : Sales_item.h  
